name: Deploy-Azure-Bicep-1-job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-bicep-github-actions-29
  WEBAPP_NAME: bicep-029


jobs:  
  preview-and-deploy:
    runs-on: [ k8s-gha-runner ]
    permissions:
        id-token: write
        contents: read    

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Install Azure Cli
      run: |  
        sudo apt-get update -y
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg -y
        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
             gpg --dearmor |
             sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
        AZ_DIST=$(lsb_release -cs)
        echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_DIST main" |
            sudo tee /etc/apt/sources.list.d/azure-cli.list     
        sudo apt-get update -y
        sudo apt-get install azure-cli -y

    - name: Login to Azure
      uses: Azure/login@v1.6.1
      with:
        #auth-type: SERVICE_PRINCIPAL
        #client-id: ${{ secrets.ARM_CLIENT_ID }}
        #tenant-id: ${{ secrets.ARM_TENANT_ID }}
        #subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

    - name: Create Azure Resource Group
      uses: Azure/cli@v1.0.8
      with:
        inlineScript: |
          az version
          az group create -n rg-bicep-github-actions-29 -l westeurope

    - name: Preview Changes fron Bicep
      uses: Azure/deployment-what-if-action@v1.0.0
      with:
        subscription: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
        resourceGroup: ${{ env.RESOURCE_GROUP }} 
        templateFile: 01-bicep-webapp/webapp-linux.bicep 
        additionalParameters: webAppName=$WEBAPP_NAME
        
    - name: Deploy Bicep to Azure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: 01-bicep-webapp/webapp-linux.bicep
        parameters: webAppName=${{ env.WEBAPP_NAME }}
        failOnStdErr: false
        scope: subscription