name: 'New Runner test worflow'

on:
  workflow_dispatch:

  pull_request:
    branches:
    - main    
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
   test-job:
     runs-on: dev-runner-npd
     steps:
       - name: Run a one-line script
         run: echo "Hello GHA workflow!" 
