name: 'New Runner Test Workflow'

on:
  push:
    branches:
    - main
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request:
    branches:
    - main
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
   build:
     runs-on: dev-runner-npd
     steps:
       - name: checkout workspace
         uses: actions/checkout@v3
         
       - name: Run a one-line script
         run: echo "Hello GHA workflow!" 

       - name: Run a multi-line script
         run: |
            echo Add other actions to build,
            echo test, and deploy your project.   
